### ISSUE TITLE
New Slim

### ISSUE THREAD

**Issue by jbcoder** [lucentx/angular-crud#1]
After running through a couple different issues setting this up I found out that with the latest version of Slim, I had to use "\Slim\Slim::registerAutoloader();" after the require statement.

Also, whenever I have a request in the index.php I had to use "\Slim\Slim::" for the requests instead of just "\Slim::"

Those two things may help anyone trying to set this up.

**Comment by marffinn** [comment]
Hello I have a problem with setting Your app on localhost. Any idea ? BTW very good tutorial - and it'll make my work easier - a LOT EASIER - If I actually find solution to this ;)

![original](https://cloud.githubusercontent.com/assets/4717667/11063722/ee09e802-87b8-11e5-9b92-b1cad31f7e0c.jpg)

**Comment by michelcmorel** [comment]
Hi Tomasz,
I can see 2 issues with your screenshot. First check that wamp is running. Your localhost address should look like http://localhost/pew 
So check documentation on setting up a localhost with wamp.
Then 2nd I can see you have access denied on AngularJS file so try to download it and re-link it to your document.
Michel

**Comment by marffinn** [comment]
Yes, I did that - this test app is one amongst other php apps such as wordpress , opencart. So serwer is running. I checked That Sli//Docs - PHP version is correct. I have to mention that I have another app written in Angular and Electron. I downloaded this app just to test it - because it looks very very very promising so to speak when incorporated into my main project, but first i need to see it running on this example.
Yes, I've tried to link local angular.min.js - to no avail :/ I love this idea of api-kinda-driven Angular app.
Please Help :(((

**Comment by michelcmorel** [comment]
Try to turn on php error reporting. Also try to do a Google Search on the error you are getting. I'm not sure what you mean by link not available. 
Also can you send me the link of the github page where you have downloaded the files?
Michel

**Comment by marffinn** [comment]
it is this repository :) I don't realy know what to say....

**Comment by michelcmorel** [comment]
Hi Tomasz,
This repo belongs to aron barbosa, maybe ask him for advises on setting up your project,
Regards,

**Comment by marffinn** [comment]
I did wrote an e-mail. Let's see what happens

**Comment by lucentx** [comment]
Oh sorry I already forgot about this project. haha. I'm updating this to use the new version of slimphp framework.

**Comment by lucentx** [comment]
I've pushed changes to the repo. It is now using new stable version of slimphp. Don't forget to run composer install / composer update since I'm using composer to install slimphp.
